/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiCoachBanner: typeof import('./components/business/AiCoachBanner.vue')['default']
    ArticleListItem: typeof import('./components/business/ArticleListItem.vue')['default']
    CategoryCard: typeof import('./components/business/CategoryCard.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    FeaturedArticle: typeof import('./components/business/FeaturedArticle.vue')['default']
    HomeRemoteState: typeof import('./components/common/HomeRemoteState.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteFooter: typeof import('./components/common/SiteFooter.vue')['default']
    SiteHeader: typeof import('./components/common/SiteHeader.vue')['default']
    TrainingPlanCard: typeof import('./components/business/TrainingPlanCard.vue')['default']
    TrendingList: typeof import('./components/business/TrendingList.vue')['default']
    VideoCard: typeof import('./components/business/VideoCard.vue')['default']
  }
}
